#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'sudo'
cookbook 'apt'
cookbook 'ruby'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'ohai'
cookbook 'git'
cookbook 'openssl'
cookbook 'monit'
cookbook 'chef-rails'
# cookbook 'chef-client'

cookbook 'nginx', '>= 1.0.0'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'postgresql',
  :git => 'https://github.com/findsyou/cookbooks',
  :ref => 'postgresql-improvements'

